# Repository configuration

data:
  main: "data/anime_transform.csv"
  cat_genres: "data/cat_genres.csv"
  cat_themes: "data/cat_themes.csv"
  preprocesados_x: "data/xtest.csv"
  preprocesados_y: "data/ytest.csv"

modelos: "modelos/"
gs_best_model_name: "mejor_modelo.pkl"

clustering:
   numerical_variables: ['score', 'number_episodes', 'members']
   categorical_variables: ['studio','demographics', 'emission_type','month', 'action', 'comedy', 'ecchi', 'slice_of_life', 'sports',
       'drama and romance', 'adventure and fantasy', 'mystery and horror',
       'sci_fi and supernatural']
   segmentation_variables: ['score', 'studio', 'number_episodes', 'demographics', 'emission_type',
       'month', 'members', 'action', 'comedy', 'ecchi', 'slice_of_life', 'sports',
       'drama and romance', 'adventure and fantasy', 'mystery and horror',
       'sci_fi and supernatural']
   preprocessor_name: "datos_preprocesados.pkl"
